name: CI

on:
  push:
    branches:
      - main  # or you could use 'master' if your main branch is named 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # or any other runner

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t frontend -f Dockerfile.dev .

    - name: Run Tests
      run: docker run -e CI=true frontend npm run test
